config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registrations => 'users/registrations'
  }
  
  root "games#index"
  
  resources :games, only: %i(index show) do
    collection do
      get :league, :cl, :euro, :scorers
    end
    resources :comments, only: %i(create destroy)
  end

  resources :rates do
    collection do
      get :best_XI
    end
  end
  
  resources :users, only: %i(show edit update)

end

app/models/game.rb
class Game < ApplicationRecord
  
  #association
  has_many :rates, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require 'json'
  require 'httpclient'
  
  def index
    set_league_matches("PL", 2021, @matchday)
    @rates = Rate.get_rates.order(id: "DESC").limit(9)
    @rankings = Player.rankings
  end
  
  def show
    @game = Game.find_or_create_by(id: params[:id])
    set_match(@game.id)
    @comments = @game.comments.includes(:user)
  end
  
  def league
    set_league_matches(params[:code], params[:year], params[:day])
    set_standings(params[:code])
  end
  
  def cl
    set_tournament_matches(params[:code], params[:year], params[:stage], params[:day])
    set_tournament_standings(params[:code])
  end
  
  def euro
    set_tournament_matches(params[:code], params[:year], params[:stage], params[:day])
    set_tournament_standings(params[:code])
  end
    
  def scorers
    result = Api::FootballData::Request.get_scorers(params[:code], params[:year])
    @scorers = result["scorers"]
  end
  
  def team
    result = Api::FootballData::Request.get_team_matches(params[:team_id])
    @matches = result['matches']
  end
  
end

app/helpers/games_helper.rb
module GamesHelper
  
  def competiton_title(code)
    if code == "PL"
      "プレミアリーグ"
    elsif code == "PD"
      "ラ・リーガ"
    elsif code == "BL1"
      "ブンデスリーガ"
    elsif code == "SA"
      "セリエＡ"
    elsif code == "FL1"
      "リーグ・アン"
    elsif code == "CL"
      "チャンピオンズリーグ"
    elsif code == "EC"
      "ユーロ2020"
    end
  end
  
  def match_date(date)
    date.in_time_zone.strftime('%Y/%m/%d')
  end
  
  def match_time(time)
    time.in_time_zone.strftime('%H:%M')
  end
  
  def scorer?(scorer, player, type)
    if scorer == player && type == "OWN"
      "OG"
    elsif scorer == player
      "G"
    end
  end
  
  def assist?(assist, player)
    "A" if assist == player 
  end
  
  def player_in?(sub, bench)
    "#{sub['minute']}' ↑" if bench['name'] == sub['playerIn']['name']
  end
  
  def player_out?(sub, start)
    "#{sub['minute']}' ↓" if start['name'] == sub['playerOut']['name']
  end
  
  def goal_team?(goal, team)
    if goal['team']['name'] == team
      if goal['type'] == "REGULAR"
        "#{goal['minute']}' #{goal['scorer']['name']}"
      elsif goal['type'] == "OWN"
        "#{goal['minute']}' #{goal['scorer']['name']}(OG)"
      elsif goal['type'] == "PENALTY"
        "#{goal['minute']}' #{goal['scorer']['name']}(PK)"
      end
    end
  end
  
  def match_scheduled?(status)
    status == "SCHEDULED"
  end
  
  def match_finished?(status)
    status == "FINISHED"
  end
  
  def penalties?(m)
    m['score']['duration'] == "PENALTY_SHOOTOUT"
  end
  
  def team_logo(team)
    "https://crests.football-data.org/#{team}.svg"
  end
  
  def ht_score(match)
    "#{match['score']['halfTime']['homeTeam']} - #{match['score']['halfTime']['awayTeam']}" 
  end
    
end

app/views/games/_like.html.erb
<% if user_signed_in? %>
<div class="my-3">
  <div class="container">
    <div class="row justify-content-start">
      <h3>いいね数: <%= @game.likes.count %></h3>
      <div class="ml-3">
        <% if current_user.already_liked?(@game) %>
          <%= button_to 'いいねを取り消す', game_like_path(@game), method: :delete, class: "btn btn-success" %>
        <% else %>
          <%= button_to 'いいね', game_likes_path(@game), class: "btn btn-outline-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/games/_member_card.html.haml
// team info 
%div.col-sm-12.col-md-6
  %div.text-center
    %h3
      = image_tag team_logo(team['id']), size: "50x50"
      = team['name']
  
  // starting lineup
  = render 'members', {header: "スタメン", members: team['lineup'], match: @match}
  
  // sub lineup
  = render 'members', {header: "サブ", members: team['bench'], match: @match}
          

app/views/games/_members.html.haml
%div.card.mb-3
  %div.card-header
    %h3.text-center= header
  %div.card-body
    - members.each do |m|
    
      // player info 
      %p
        = m['shirtNumber'] 
        = m['position']
        = m['name']
        &nbsp;
        
        // Goal/Assist
        - match['goals'].each do |g|
          %strong.text-primary= scorer?(g['scorer']['name'], m['name'], g['type'])
          %strong.text-dark= assist?(g['assist']['name'], m['name']) if g['assist'].present?
        &nbsp;
        
        // sub
        - match['substitutions'].each do |sub|
          %strong.text-danger= player_out?(sub, m)
          %strong.text-success= player_in?(sub, m)

app/views/games/_score_card.html.haml
%div.card.container.my-3
  %div.row
    // home team
    = render 'games/score_info', {team: match['homeTeam'], goals: match['goals']}
    
    // score
    %div.col-4.text-center.pt-2.my-3
      %h1
        = match['score']['fullTime']['homeTeam']
        = "-"
        = match['score']['fullTime']['awayTeam']
        .text-muted.mt-2
          %h6= match_date(match['utcDate'])
          %h6= "@#{match['venue']}"
          %h6 HTスコア
          %h6= ht_score(match) if match_finished?(match['status'])
          
    // away team
    = render 'games/score_info', {team: match['awayTeam'], goals: match['goals']}

app/views/games/_score_info.html.haml
%div.col-4.pt-2.text-center.my-3
  .mb-3= image_tag team_logo(team['id']), size: "80x80"
  - goals.each do |g|
    %p= goal_team?(g, team['name'])

app/views/games/_standings.html.haml
// title
%h1.midasi 順位表

// standings
%table.table
  %thead.thead
    %tr
      %th 順位
      %th クラブ
      %th 試合
      %th 勝
      %th 分
      %th 負
      %th Pts
      
  %tbody
    - standings.each do |s|
      %tr
        %td= s["position"]
        %td
          = image_tag team_logo(s["team"]["id"]), size: "30x30"
          %h6.d-none.d-md-block= s["team"]["name"]
        %td= s["playedGames"]
        %td= s["won"]
        %td= s["draw"]
        %td= s["lost"]
        %td= s["points"]

app/views/games/_tournament_standings.html.haml
// title 
%h1.midasi 順位表

// standings
%div.container-fluid
  %div.row.d-flex.align-items-center.justify-content-center
    - standings.each do |s|
      %div.col-xs-12.mx-3.my-3
        %h5.text-center.midasi= s['group']
        %table.table.fadein
          %thead
            %tr.text-center
              %th 順位
              %th クラブ
              %th 試合
              %th 勝
              %th 分
              %th 負
              %th Pts
          %tbody
            - s['table'].each do |t|
              %tr.text-center
                %td= t['position']
                %td= image_tag team_logo(t['team']['id']), size: "30x30"
                %td= t['playedGames']
                %td= t['won']
                %td= t['draw']
                %td= t['lost']
                %td= t['points']

app/views/games/cl.html.haml
// title
%h1= link_to competiton_title(params[:code]), cl_games_path(code: params[:code], year: "", stage: "GROUP_STAGE", day: 1), class: "midasi"

%div.container 
  %div.d-flex.justify-content-center
    %div.row
    
      // season button
      %div.dropdown.mx-1.my-1
        %button#dropdownMenuButton.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          シーズン
        %div.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          = link_to "現在のシーズン", cl_games_path(code: params[:code], year: "", day: 1), class: "dropdown-item" 
          = link_to "20-21シーズン", cl_games_path(code: params[:code], year: 2020, day: 1), class: "dropdown-item" 
          = link_to "19-20シーズン", cl_games_path(code: params[:code], year: 2019, day: 1), class: "dropdown-item" 
          = link_to "18-19シーズン", cl_games_path(code: params[:code], year: 2018, day: 1), class: "dropdown-item" 
      
      // matchday button
      %div.dropdown.mx-1.my-1
        %button#dropdownMenuButton.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          節
        %div.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          - 6.times do |i|
            = link_to "#{i + 1}節",  cl_games_path(code: params[:code], year: params[:year], stage: "GROUP_STAGE", day: (i + 1)), class: "dropdown-item" 
          = link_to "ラウンド・オブ・16", cl_games_path(code: params[:code], year: params[:year], stage: "ROUND_OF_16"), class: "dropdown-item"
          = link_to "準々決勝", cl_games_path(code: params[:code], year: params[:year], stage: "QUARTER_FINALS"), class: "dropdown-item"
          = link_to "準決勝", cl_games_path(code: params[:code], year: params[:year], stage: "SEMI_FINALS"), class: "dropdown-item"
          = link_to "決勝", cl_games_path(code: params[:code], year: params[:year], stage: "FINAL"), class: "dropdown-item"
       
      // score ranking button 
      %div.mx-1.my-1
        = link_to "得点ランキング",  scorers_games_path(code: params[:code], year: params[:year]), class: "btn"
  
  // matches
  %div.mt-3
    = render 'games', matches: @matches
    
    standings
    %div.fadein
      = render 'tournament_standings', standings: @standings

app/views/games/euro.html.haml
// title
%h1= link_to competiton_title(params[:code]), euro_games_path(code: params[:code], year: "", day: 1), class: "midasi"
 
 
%div.container
  %div.d-flex.justify-content-center
    %div.row
    
      // matchday button
      %div.dropdown.mx-1.my-1
        %button#dropdownMenuButton.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          節
        %div.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          - 3.times do |i|
            = link_to "グループステージ第#{i + 1}節", euro_games_path(code: params[:code], year: params[:year], day: (i + 1)), class: "dropdown-item" 
          = link_to "ラウンド16", euro_games_path(code: params[:code], year: params[:year], stage: "LAST_16"), class: "dropdown-item"
          = link_to "準々決勝", euro_games_path(code: params[:code], year: params[:year], stage: "QUARTER_FINAL"), class: "dropdown-item"
          = link_to "準決勝", euro_games_path(code: params[:code], year: params[:year], stage: "SEMI_FINAL"), class: "dropdown-item"
          = link_to "決勝", euro_games_path(code: params[:code], year: params[:year], stage: "FINAL"), class: "dropdown-item"
          
      // score ranking button    
      %div.mx-1.my-1
        = link_to "得点ランキング",  scorers_games_path(code: params[:code], year: params[:year]), class: "btn"
  
  // match info
  %div.mt-3
    = render 'games', matches: @matches
    
    // standings
    %div.fadein
      = render 'tournament_standings', standings: @standings

app/views/games/index.html.haml
%div.container.mt-3

  // pickup matches
  %h1.midasi 今週のピックアップマッチ 
  = render 'games', matches: @matches
 
 
%div.container
  %div.row.d-flex.justify-content-center
  
    // rates
    %div.col-12     
      %h1.midasi 最新の投稿
      = render 'rates/rate_card', rates: @rates
      .text-center= link_to "投稿一覧へ", rates_path, class: "midasi"
    
    // player rankings
    %div.col-12.col-lg-4.fadein
      %h1.midasi 選手ランキング
      %table.table
        %thead
          %tr
            %th 順位
            %th 選手
            %th 評価
      
        %tbody
          - @rankings.average(:player_rate).each_with_index do |r, i|
            %tr
              %td= i + 1
              %td.text-left
                = image_tag team_logo(@rankings[i].team_id), size: "30x30"
                = r[0]
              %td= r[1].round(1)
          

app/views/games/league.html.haml
// title
%h1= link_to competiton_title(params[:code]), league_games_path(code: params[:code], year: "", day: 1), class:"midasi"

%div.container
  %div.d-flex.justify-content-center
    %div.row
      
      // season button
      %div.dropdown.mx-1.my-1
        %button#dropdownMenuButton.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          シーズン
        %div.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          = link_to "現在のシーズン", league_games_path(code: params[:code], year: "", day: 1), class: "dropdown-item" 
          = link_to "20-21シーズン", league_games_path(code: params[:code], year: 2020, day: 1), class: "dropdown-item" 
          = link_to "19-20シーズン", league_games_path(code: params[:code], year: 2019, day: 1), class: "dropdown-item" 
          = link_to "18-19シーズン", league_games_path(code: params[:code], year: 2018, day: 1), class: "dropdown-item" 
      
      // matchday button      
      %div.dropdown.mx-1.my-1
        %button#dropdownMenuButton.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          節
        %div.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          - 38.times do |i|
            = link_to "#{i + 1}節",  league_games_path(code: params[:code], year: params[:year], day: (i + 1)), class: "dropdown-item"
      
      // score ranking button        
      %div.mx-1.my-1
        = link_to "得点ランキング",  scorers_games_path(code: params[:code], year: params[:year]), class: "btn"
  
  // matches      
  %div.mt-3
    = render 'games', matches: @matches
    
    // standings
    %div.fadein
      = render 'standings', standings: @standings

app/views/games/scorers.html.haml
// title
%h1.midasi= "#{competiton_title(params[:code])}・得点ランキング"

// table
%div.container-fluid
  %div.row.d-flex.align-items-center.justify-content-center
    %div.col-xs-12.col-md-10
      %table.table
        %thead
          %tr
            %th 順位
            %th 選手
            %th ゴール数
      
        %tbody
          - @scorers.each_with_index do |s, i|
            %tr
              %td= i + 1
              %td.text-left
                = image_tag team_logo(s['team']['id']), size: "30x30"
                = s['player']['name']
              %td= s['numberOfGoals']

app/views/games/show.html.haml
// new rate button
%div.mt-2.text-right
  = link_to '評価する', new_rate_path(game_id: params[:id]), class: "btn" if match_finished?(@match['status'])
  
// score card
= render 'score_card', match: @match

// members   
%div.container.mt-2
  %div.row.d-flex.justify-content-between
    = render 'member_card', team: @match['homeTeam']
    = render 'member_card', team: @match['awayTeam']

// comment
%div.container.my-3
  = render 'comments/comments', comments: @comments
  = render 'comments/form', game: @game

app/views/games/standings.html.haml
%h1 順位表

%table.table
  %thead
    %tr.text-center
      %th 順位
      %th クラブ
      %th 試合
      %th 勝
      %th 分
      %th 負
      %th Pts
      
  %tbody
    - @standings.each do |s|
      %tr.text-center
        %td= s["position"]
        %td
          = image_tag "https://crests.football-data.org/#{s["team"]["id"]}.svg", size: "30x30"
          = s["team"]["name"]
        %td= s["playedGames"]
        %td= s["won"]
        %td= s["draw"]
        %td= s["lost"]
        %td= s["points"]