config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registrations => 'users/registrations'
  }
  
  root "games#index"
  
  resources :games, only: %i(index show) do
    collection do
      get :league, :cl, :euro, :scorers
    end
    resources :comments, only: %i(create destroy)
  end

  resources :rates do
    collection do
      get :best_XI
    end
  end
  
  resources :users, only: %i(show edit update)

end

app/models/rate.rb
class Rate < ApplicationRecord
  
  # association
  belongs_to :game
  belongs_to :user
  
  has_many :players, dependent: :destroy
  
  # scope
  scope :get_rates, -> { includes(:user).includes(:players).order(id: "DESC") } 
  scope :paginate, -> (params, count) { page(params).per(count).order(id: "DESC") }
  
  # search method
  def self.search(search)
    search ? (where(['home_team LIKE ? OR away_team LIKE ?', "%#{search}%" ,"%#{search}%"])) : (all)
  end

end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :authenticate_user!, except: %i(index show best_XI)
  
  def index
    @rates = Rate.get_rates.paginate(params[:page], 15).search(params[:search])
  end
  
  def show
    @rate = Rate.find(params[:id])
    set_match(@rate.game_id)
  end
  
  def new 
    set_match(params[:game_id])
    @home = set_members(@match['homeTeam'])
    @away = set_members(@match['awayTeam'])
    @rate = RateForm.new
  end
  
  def create
    @rate = RateForm.new
    @rate.assign_attributes(rate_form_params)
    if @rate.save
      redirect_to rates_path
    else
      redirect_to new_rate_path(game_id: @rate.game_id)
    end
  end
  
  def destroy
    rate = Rate.find(params[:id])
    if rate.user_id == current_user.id
      rate.destroy 
      redirect_to rates_path
    else
      redirect_to rate
    end
  end
  
  def best_XI
    player = Player.group_best
    @gk = player.best("Goalkeeper", 1)
    @df = player.best("Defender", 4)
    @mf = player.best("Midfielder", 3)
    @fw = player.best("Attacker", 3)
  end
  
  private
  def rate_form_params
    params.require(:rate_form).permit(:home_team, :away_team, :game_id,
    players_attributes: [:name, :player_rate, :rate_text, :position, :shirtnumber, :team_id])
    .merge(user_id: current_user.id)
  end
  
  def set_members(team)
    sub = @match['substitutions'].select {|s| s['team']['name'] == team['name'] } 
    sub.each do |s|
      team['lineup'] << { "name" => s['playerIn']['name'], 
                          "position" => sub_position(team['bench'], s['playerIn']['name']), 
                          "shirtNumber" => sub_number(team['bench'], s['playerIn']['name']) }
    end
    team['lineup']
  end
  
  def sub_position(bench, player)
    bench.select { |b| b['name'] == (player) }[0]['position']
  end
  
  def sub_number(bench, player)
    bench.select { |b| b['name'] == (player) }[0]['shirtNumber']
  end

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_field_form.html.haml
// shirtnumber
%div.col-12.col-md-2.col-lg-1.mb-1
  %div.form_group
    = f.number_field :shirtnumber, value: player['shirtNumber'], name: "rate_form[players_attributes][][shirtnumber]", :readonly => true, class: "form-control"

// position
%div.col-xs-12.col-md-2.mb-1
  %div.form_group
    = f.text_field :position, value: player['position'], name: "rate_form[players_attributes][][position]", :readonly => true, class: "form-control"

// player name
%div.col-12.col-md-2.mb-1
  %div.form_group
    = f.text_field :name, value: player['name'], name: "rate_form[players_attributes][][name]", :readonly => true , class: "form-control"

// rate
%div.col-12.col-md-2.col-lg-3.mb-1
  %div.range
    = f.range_field :player_rate, :in => 1..10, :step => 1, :value => 6, name: "rate_form[players_attributes][][player_rate]"
    %span.score 6

// comment   
%div.col-12.col-md-4.col-lg-4.mb-3
  %div.form_group
    = f.text_area :rate_text, :placeholder => "コメントを入力", name: "rate_form[players_attributes][][rate_text]", class: "form-control"

    = f.hidden_field :team_id, value: team_id, name: "rate_form[players_attributes][][team_id]"



// show value for range_field
:javascript
  var elem = document.getElementsByClassName('range');
  var rangeValue = function (elem, target) {
    return function(evt){
      target.innerHTML = elem.value;
    }
  }
  for(var i = 0, max = elem.length; i < max; i++){
    bar = elem[i].getElementsByTagName('input')[0];
    target = elem[i].getElementsByTagName('span')[0];
    bar.addEventListener('input', rangeValue(bar, target));
  }
    

app/views/rates/_form.html.haml
// title
%h1
  = image_tag team_logo(team['id']), size: "50x50"
  = team['name']

// player info  
%div.container
  %div.row
    - players.each do |p|
      = form.fields_for :players do |f|
        = render 'field_form', {f: f, player: p, team_id: team['id']}
        

app/views/rates/_player.html.haml
=image_tag team_logo(player.team_id), size: "50x50"
%h6.text-white= player.name

app/views/rates/_rate_card.html.haml
// rate info 
%div.row.d-flex.align-items-center.justify-content-center
  - rates.each do |r|
    %div.card.col-12.col-lg-3.my-2.mx-1.fadein
    
      // user name
      %div.mt-2
        %span.user-name= r.user.name
        
      = link_to rate_path(r.id) do
        %div.card-body.row.d-flex.align-items-center
        
          // home team
          %div.col-6.text-center
            = image_tag team_logo(r.players.first.team_id), size: "60x60" if r.players.present?
            
          // away team
          %div.col-6.text-center
            = image_tag team_logo(r.players.last.team_id), size: "60x60" if r.players.present?
       
      // date created 
      %small.text-muted.text-right.pb-2= r.created_at.strftime('%Y/%m/%d')

app/views/rates/_search.html.haml
// form
%div.d-flex.justify-content-center
  = form_with url: rates_path, method: :get, html: { class: "form-inline mt-2" }, local: true do |form|
    = form.search_field :search, :placeholder => "チーム名を入力", class: "form-control mr-2"
    = form.submit "search", class: "btn d-none d-lg-block"

app/views/rates/best_XI.html.haml
// title
%h1.midasi FootRateベストXI

%div.container.bg-success

  // attacker
  %div.row
    - @fw.each do |fw|
      %div.col-4.text-center.my-3
        = render 'rates/player', player: fw
        
  // midfieder       
  %div.row
    - @mf.each do |mf|
      %div.col-4.text-center.my-3
        = render 'rates/player', player: mf
  
  // defender      
  %div.row
    - @df.each do |df|
      %div.col-3.text-center.my-3
        = render 'rates/player', player: df
        
  // goalkeeper     
  %div.text-center.my-3
    - @gk.each do |gk|
      = render 'rates/player', player: gk

app/views/rates/index.html.haml
// title
%h1.text-center= link_to "投稿一覧", rates_path, class: "midasi"

// search form
= render 'search'

// rates      
%div.container.mt-3.py-3  
  = render 'rate_card', rates: @rates 

// pagination  
%div.mt-3  
  = paginate @rates
  

app/views/rates/new.html.haml
// title
%h1.midasi 新規投稿

// form
= form_with model: @rate, url: rates_path, local: true do |form|
  
  // game info
  =form.hidden_field :home_team, value: @match['homeTeam']['name']
  =form.hidden_field :away_team, value: @match['awayTeam']['name']
  =form.hidden_field :game_id, value: params[:game_id]
  
  // home team form
  = render 'form', {form: form, team: @match['homeTeam'], players: @home}
  
  // away team form
  = render 'form', {form: form, team: @match['awayTeam'], players: @away}      
  
  // submit button
  .text-right= form.submit "投稿する", class: "btn"

app/views/rates/show.html.haml
// gmes/show button
.text-right= link_to "試合の詳細", game_path(@rate.game_id), class: "btn my-2"

// score card
= render 'games/score_card', match: @match

// info 
%p.text-right= "投稿日: #{@rate.created_at.strftime('%Y/%m/%d')}"
%h1.midasi= "#{@rate.user.name}の投稿"
.text-right= link_to "削除", "/rates/#{@rate.id}", method: :delete, data: { confirm: "削除しますか？" } , class: "btn danger" if same_user?(@rate.user)


// rates
- @rate.players.each do |p|
  %div.card.my-2.fadein
    %div.card-body
      %h5.card-title
        = image_tag team_logo(p.team_id), size: "40x40"
        = "#{p.shirtnumber}・#{p.position }"
      %h5.card-title= p.name
      %p.text-muted= "評価：#{p.player_rate}"
      %p.card-text= simple_format(p.rate_text) 